# Generated by Django 3.2.5 on 2021-07-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='allergy_products',
            new_name='Allergy_Product',
        ),
        migrations.RenameModel(
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='nutritions',
            new_name='Nutrition',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='Product',
        ),
        migrations.AlterModelTable(
            name='allergy',
            table='allergy',
        ),
        migrations.AlterModelTable(
            name='allergy_product',
            table='allergy_products',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='nutrition',
            table='nutritions',
        ),
    ]
